# -*- coding: utf-8 -*-
"""Howdoi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UXoOTvS7KmiwIi2X-fPl1nbYumFjYQr-
"""

pip install howdoi

!howdoi current version of pyhton

!howdoi use of pyhton

!howdoi make trees in Python

!howdoi What libraries can I use to visualize tree

!howdoi How can I implement a tree traversal algorithm in Python